/**
 * GHOST TAX — FOUNDER MISSION CONTROL
 * Seed data v2 — Decision-oriented, with attackability + deal potential + weaknesses
 */

import type { Account } from '@/types/command';

const NOW = '2026-03-16T12:00:00Z';

export const SEED_ACCOUNTS: Account[] = [
  {
    id: 'upvest',
    company: 'Upvest',
    domain: 'upvest.co',
    country: 'DE',
    industry: 'Investment Infrastructure API',
    employeeRange: '200-300',
    website: 'https://upvest.co',
    status: 'new',
    score: 25,
    tier: 1,
    attackability: 'now',
    dealPotential: 'medium',
    conviction: 'very_high',
    solofit: 'ideal',
    financeLead: { name: 'Julian Lange', title: 'CFO', background: 'CFO seul, recrute VP/Director Finance. Job posting live.' },
    signals: [
      { type: 'hiring', detail: 'VP/Director of Finance — live job posting (Ashby + Remotive)', source: 'Ashby', strength: 5 },
      { type: 'funding', detail: '$104.6M funding Dec 2024, Deutsche Bank partnership', source: 'Crunchbase', date: '2024-12', strength: 4 },
      { type: 'growth', detail: '100M+ orders in 2025 (5x YoY)', source: 'Company PR', date: '2025-12', strength: 4 },
    ],
    mainSignal: 'Recrute VP/Director Finance — le CFO manque de bande passante',
    whyNow: 'Le VP Finance arrive dans 2-3 mois. Un scan AVANT son arrivée = baseline day-1 au lieu de month-3. Fenêtre 4-8 semaines.',
    hypothesis: {
      summary: 'Fintech réglementée en scaling sans VP Finance = visibilité limitée sur les coûts logiciels.',
      whyItMatters: 'Le CFO gère seul. Compliance + cloud + dev tools croissent plus vite que le headcount.',
      hiddenExposure: ['Dev tools scaling per-seat', 'Cloud costs non-linéaires (API infra)', 'Compliance tools empilés', 'Contrats non renégociés'],
      proofNeeded: 'Scan Exa de la stack via job postings + intégrations techniques.',
    },
    strengths: ['Signal temporel exceptionnel (recrutement live)', 'CFO identifié par nom', 'Taille parfaite pour solofounder', 'Angle naturel et non-agressif'],
    weaknesses: ['Deal potential modéré (startup 200-300)', 'Pas de preuve directe de waste'],
    outreach: [
      { channel: 'linkedin', body: 'Julian,\n\nI noticed Upvest is hiring a VP/Director of Finance. That role usually gets created when financial complexity outgrows the current structure — especially in regulated fintech scaling fast.\n\nBefore that person arrives and spends their first quarter mapping costs: I run financial exposure scans for B2B tech companies. The output is a structured diagnostic of where SaaS and cloud spend may be drifting — typically 12-20% of annual software costs in companies at your stage.\n\nWould a quick scan of Upvest\'s exposure be useful as a baseline for the incoming VP Finance?\n\n— Jean-Étienne', hook: 'VP Finance hire = scan as day-1 baseline', status: 'draft' },
      { channel: 'email', subject: 'Upvest — VP Finance hire + a potential head start', body: 'Julian,\n\nThe VP/Director of Finance role you\'re hiring for tells a clear story: the financial complexity is outgrowing the current setup. That\'s normal for regulated fintech in scaling mode.\n\nI work with B2B tech companies to detect hidden financial exposure in their SaaS, cloud, and software spend. The pattern I see repeatedly: fintech companies between 200-500 employees carry 12-20% in invisible software waste.\n\nA quick diagnostic before your VP Finance starts could:\n1. Give them a baseline on day one instead of month three\n2. Surface the highest-priority cost lines before renewal season\n3. Quantify the gap between headcount growth and license growth\n\nNo call needed. I can run a scan and deliver a structured exposure report. If the numbers are meaningful, we talk. If not, you\'ve lost nothing.\n
Jean-Étienne
Ghost Tax — ghost-tax.com', hook: 'VP Finance hire = scaling pain', status: 'draft' },
      { channel: 'followup', subject: 'Re: Upvest — VP Finance hire', body: 'Julian — quick follow-up.\n\nThe average B2B SaaS company now spends $9,100/employee/year on software (Zylo 2026). For a 250-person fintech: ~$2.3M in annual SaaS spend. Industry benchmarks show 15-25% is invisible waste. That\'s $350k-$575k/year.\n\nA 30-minute scan would tell you if Upvest is in that range.\n\n— Jean-Étienne', hook: '$2.3M SaaS spend benchmark', status: 'draft' },
      { channel: 'short', body: 'Julian — you\'re hiring a VP Finance. Before they spend Q1 mapping costs, would a pre-built exposure scan be useful? 48h, no call. ghost-tax.com', hook: 'Ultra-direct', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'VP/Director Finance job posting found on Ashby', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
      { type: 'message_prepared', detail: '4 outreach messages drafted (LI, email, follow-up, short)', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 5000,
    nextAction: 'Trouver Julian Lange sur LinkedIn + envoyer connexion',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'solaris',
    company: 'Solaris SE',
    domain: 'solarisbank.com',
    country: 'DE',
    industry: 'Banking-as-a-Service',
    employeeRange: '~500',
    website: 'https://solarisbank.com',
    status: 'new',
    score: 23,
    tier: 1,
    attackability: 'now',
    dealPotential: 'high',
    conviction: 'high',
    solofit: 'good',
    financeLead: { name: 'Lee Johnstone', title: 'CFO (new)', background: 'Promu depuis MD Solaris UK. Nouveau dans le rôle CFO pendant restructuration majeure.' },
    signals: [
      { type: 'restructuring', detail: '-1/3 effectifs (de ~700 à ~500)', source: 'Tech.eu', strength: 5 },
      { type: 'regulatory', detail: 'Pression BaFin — AML, monitoring spécial depuis 2022', source: 'FintechFutures', strength: 5 },
      { type: 'funding', detail: '€140M Series G (Feb 2025)', source: 'Fintech Global', date: '2025-02', strength: 4 },
      { type: 'divestment', detail: 'Vente filiale UK Engage', source: 'FintechFutures', strength: 3 },
    ],
    mainSignal: 'Restructuration -33% + nouveau CFO + pression BaFin',
    whyNow: 'Post-restructuration = chaque coût scruté. Licences des 250 départs encore actives. Le CFO doit prouver le contrôle. Fenêtre 2-4 mois.',
    hypothesis: {
      summary: '~250 départs mais contrats SaaS annuels toujours actifs. Licences zombies quasi certaines.',
      whyItMatters: 'Triple pression: board (ROI €140M), BaFin (compliance), marché (viabilité). Chaque euro de waste identifié renforce la crédibilité du CFO.',
      hiddenExposure: ['Licences SaaS des ~250 départs', 'Contrats entité UK non résiliés', 'Cloud surdimensionné pour effectif réduit', 'Compliance tools empilés sous pression BaFin'],
      proofNeeded: 'Scan pour quantifier le gap headcount actuel (~500) vs licences actives. Benchmark: 15-25% waste post-restructuration.',
    },
    strengths: ['Convergence de signaux exceptionnelle', 'Douleur financière quasi certaine (post-layoffs)', 'Deal potential élevé (500 emp, BaaS)', 'CFO sous pression = réceptif'],
    weaknesses: ['Entreprise sous stress = timing délicat', 'CFO nouveau = peut ne pas prioriser ça', 'Processus corporate possible malgré la taille'],
    outreach: [
      { channel: 'linkedin', body: 'Lee,\n\nSolaris has been through a significant restructuring. One thing that consistently gets missed post-downsizing: the SaaS and cloud licenses attached to roles that no longer exist.\n\nWhen headcount drops by a third, the contracts don\'t auto-adjust. The waste compounds — typically 15-25% of remaining software budget.\n\nI run financial exposure scans that map this gap. Would that diagnostic be useful?\n\n— Jean-Étienne', hook: 'Post-layoff license gap', status: 'draft' },
      { channel: 'email', subject: 'Post-restructuring — the cost line that doesn\'t auto-adjust', body: 'Lee,\n\nAfter a restructuring as significant as Solaris\'s, most cost lines get reviewed. One that rarely does: SaaS and cloud licensing.\n\nWhen ~250 people leave, their tools don\'t. Annual contracts keep billing. The gap compounds at 15-25% of annual software spend.\n\nI specialize in detecting this kind of hidden financial exposure. A scan could quantify zombie licenses, oversized cloud, and renewals to renegotiate.\n\nGiven the Series G and BaFin context, I imagine every identified euro matters.\n
Jean-Étienne — ghost-tax.com', hook: 'Contracts don\'t auto-adjust', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'Restructuring -33% workforce detected', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
      { type: 'message_prepared', detail: '2 outreach messages drafted', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 15000,
    nextAction: 'Trouver Lee Johnstone sur LinkedIn + connexion angle restructuration',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'mambu',
    company: 'Mambu',
    domain: 'mambu.com',
    country: 'NL',
    industry: 'Cloud Banking Platform',
    employeeRange: '~400',
    website: 'https://mambu.com',
    status: 'new',
    score: 23,
    tier: 1,
    attackability: 'now',
    dealPotential: 'high',
    conviction: 'high',
    solofit: 'good',
    financeLead: { name: 'Jesper', title: 'CFO (new)', background: 'Ex-Avaloq Group CFO, ex-Oracle VP Finance Cloud. Comprend les coûts cloud intimement.' },
    signals: [
      { type: 'executive', detail: 'Nouveau CFO — ex-Avaloq Group CFO, ex-Oracle VP Finance Cloud', source: 'FinTech Magazine', strength: 5 },
      { type: 'complexity', detail: 'Cloud banking platform = infra multi-cloud massive', source: 'Analyse', strength: 4 },
      { type: 'geography', detail: 'Dual HQ Amsterdam/Berlin = duplication opérationnelle', source: 'Site web', strength: 3 },
    ],
    mainSignal: 'Nouveau CFO (ex-Oracle Cloud) en phase d\'onboarding 90 jours',
    whyNow: 'Un CFO dans ses 90 premiers jours fait TOUJOURS un audit. Jesper vient d\'Oracle Cloud — il sait que l\'infra est opaque. Fenêtre 1-2 mois.',
    hypothesis: {
      summary: 'Cloud banking platform avec nouveau CFO héritant d\'une stack construite pour la vitesse, pas pour le contrôle des coûts.',
      whyItMatters: 'Nouveau CFO ex-Oracle/Avaloq cherche des quick wins pour établir sa crédibilité au board.',
      hiddenExposure: ['Multi-cloud (AWS + GCP probable)', 'Monitoring/observability empilés', 'Dev tools pour ~400 employés', 'Duplication tools Amsterdam/Berlin'],
      proofNeeded: 'Scan stack technique via job postings + tech blog + GitHub.',
    },
    strengths: ['CFO profile cloud-aware = comprend immédiatement', 'Timing onboarding 90j = cherche des données', 'Cloud banking = infrastructure spend élevé', 'Taille accessible'],
    weaknesses: ['CFO prénom seul — besoin de trouver le nom complet', 'Peut être déjà en audit interne', 'Dual HQ = plus de parties prenantes'],
    outreach: [
      { channel: 'linkedin', body: 'Jesper,\n\nCongratulations on the CFO role at Mambu. Coming from Avaloq and Oracle Cloud, you know how infrastructure costs can be opaque — especially in cloud-native platforms.\n\nI run financial exposure scans for B2B tech companies. For cloud banking platforms, the pattern: monitoring stacked on monitoring, cloud costs growing faster than revenue, contracts signed by engineering without finance review.\n\nIf a quick diagnostic would be useful in your first 90 days, I can deliver one in 48h.\n\n— Jean-Étienne', hook: '90-day CFO shortcut', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'New CFO ex-Avaloq/Oracle appointed', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 12000,
    nextAction: 'Trouver le nom complet du CFO Jesper sur LinkedIn',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'razor',
    company: 'Razor Group',
    domain: 'razor-group.com',
    country: 'DE',
    industry: 'E-commerce Aggregator',
    employeeRange: '500-700',
    website: 'https://razor-group.com',
    status: 'new',
    score: 23,
    tier: 1,
    attackability: 'now',
    dealPotential: 'high',
    conviction: 'high',
    solofit: 'good',
    financeLead: { name: 'Jörg Meiner', title: 'CFO', background: 'CFO pilotant l\'intégration post-merger avec Infinite Commerce.' },
    signals: [
      { type: 'M&A', detail: 'Merger Infinite Commerce finalisé Aug 2025', source: 'PRNewswire', date: '2025-08', strength: 5 },
      { type: 'funding', detail: '$1B cumul (BlackRock, Fortress)', source: 'Crunchbase', strength: 4 },
      { type: 'complexity', detail: 'Deux stacks e-commerce complètes en parallèle', source: 'Analyse', strength: 4 },
    ],
    mainSignal: 'Post-merger Infinite Commerce (Aug 2025) — deux stacks parallèles',
    whyNow: '6 mois post-merger = intégration technique en cours. Deux stacks complètes = duplication massive. BlackRock/Fortress attendent des synergies. Fenêtre 3-6 mois.',
    hypothesis: {
      summary: 'Duplication post-merger: deux CRM, deux ERP, deux analytics, deux cloud. Chaque mois = cash burn inutile.',
      whyItMatters: 'Les investisseurs attendent des synergies. La consolidation d\'outils est quantifiable et rapide vs restructuration humaine.',
      hiddenExposure: ['Deux stacks e-commerce parallèles', 'Deux contrats cloud non consolidés', 'Deux sets d\'outils logistiques', 'Contrats sous anciens noms d\'entités'],
      proofNeeded: 'Cross-scan razor-group.com + Infinite Commerce pour mapper le chevauchement techno.',
    },
    strengths: ['Post-merger = cas d\'usage textbook pour audit spend', 'CFO identifié', '$1B funding = deal potential élevé', 'Board-level urgency'],
    weaknesses: ['500-700 emp = plus corporate', 'Post-merger = organisation chaotique', 'Peut avoir déjà mandaté un consultant Big 4'],
    outreach: [
      { channel: 'linkedin', body: 'Jörg,\n\nSix months post-merger with Infinite Commerce — the tool consolidation question must be very real. Two complete tech stacks running in parallel.\n\nI quantify exactly where duplication sits and what running parallel stacks costs annually. Typical finding: 20-30% SaaS overlap.\n\nWould a consolidation scan be useful for the next board synergy discussion?\n\n— Jean-Étienne', hook: 'Post-merger stack duplication', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'Merger with Infinite Commerce detected', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 20000,
    nextAction: 'Trouver Jörg Meiner sur LinkedIn + connexion angle synergies',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'circula',
    company: 'Circula',
    domain: 'circula.com',
    country: 'DE',
    industry: 'Expense Management SaaS',
    employeeRange: '~142',
    website: 'https://circula.com',
    status: 'new',
    score: 23,
    tier: 1,
    attackability: 'soon',
    dealPotential: 'low',
    conviction: 'moderate',
    solofit: 'ideal',
    financeLead: { name: 'Johannes Kochs', title: 'CFO', background: 'Ex-SVP Finance Staffbase. A vécu le scaling startup → unicorn.' },
    signals: [
      { type: 'transformation', detail: '"On course for transformation and growth" — annonce officielle', source: 'Circula blog', strength: 4 },
      { type: 'funding', detail: '€15M extended Series A (May 2025)', source: 'Silicon Canals', date: '2025-05', strength: 3 },
      { type: 'growth', detail: '2,800 clients dont Aston Martin, DATEV', source: 'Company PR', strength: 3 },
    ],
    mainSignal: 'Phase de transformation + CFO ex-Staffbase qui connaît le waste du scaling',
    whyNow: 'Le CFO restructure les opérations. Venant de Staffbase (unicorn), il sait que la croissance crée du waste. Cherche des données.',
    hypothesis: {
      summary: 'Ironie: Circula aide ses clients à contrôler leurs dépenses, mais en transformation rapide, leur propre stack échappe probablement au scrutin.',
      whyItMatters: 'Un CFO ex-Staffbase a vu ce que le scaling fait aux coûts. En transformation, il cherche des données objectives.',
      hiddenExposure: ['Stack dev/engineering en croissance', 'Cloud pour SaaS de plus en plus complexe', 'Compliance DACH', 'Redondance outils internes vs produit'],
      proofNeeded: 'Scan ciblé pour tester l\'hypothèse ironique.',
    },
    strengths: ['CFO identifié, profil pertinent', 'Angle ironique mémorable et désarmant', 'Taille idéale pour solofounder', 'Conversion potentiellement rapide'],
    weaknesses: ['Deal potential faible (~142 emp)', 'Signal moins fort que les 4 premiers', 'Hypothèse plus spéculative que factuelle', 'Ticket €490 seulement probable'],
    outreach: [
      { channel: 'linkedin', body: 'Johannes,\n\nHonest question for the CFO of an expense management company: when was the last time someone audited Circula\'s own software spend?\n\nIn a "transformation and growth" phase, the internal stack evolves faster than the controls. Coming from Staffbase, you\'ve seen this pattern at scale.\n\nI run exposure scans for B2B tech. 48h, structured diagnostic. If the cobbler is well shod, the scan confirms it. If not — you\'d want to know.\n\n— Jean-Étienne', hook: 'Is the cobbler well shod?', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'Transformation phase announced', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 3000,
    nextAction: 'Scanner d\'abord — valider l\'hypothèse avant outreach',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'pricefx',
    company: 'Pricefx',
    domain: 'pricefx.com',
    country: 'DE',
    industry: 'AI Pricing Management',
    employeeRange: '~400',
    website: 'https://pricefx.com',
    status: 'new',
    score: 23,
    tier: 2,
    attackability: 'soon',
    dealPotential: 'medium',
    conviction: 'high',
    solofit: 'good',
    financeLead: { name: 'Gary Sher', title: 'CFO (new — March 2025)', background: 'Nommé Mars 2025. Aussi nouveau CMO = phase de restructuration opérationnelle.' },
    signals: [
      { type: 'executive', detail: 'Nouveau CFO Gary Sher nommé Mars 2025', source: 'BusinessWire', date: '2025-03', strength: 5 },
      { type: 'growth', detail: '38% YoY subscription revenue, $59.9M revenue', source: 'Company PR', strength: 4 },
      { type: 'funding', detail: '$131M total funding', source: 'Crunchbase', strength: 3 },
    ],
    mainSignal: 'Nouveau CFO (~12 mois) + 38% croissance subscription = phase d\'optimisation',
    whyNow: 'Gary Sher a terminé son audit initial (12 mois). Entre en phase d\'exécution des optimisations. Cherche des données pour justifier les coupes.',
    hypothesis: {
      summary: 'Pricefx aide ses clients à optimiser leurs prix — mais qui optimise leur propre spend pendant une croissance de 38%?',
      whyItMatters: 'AI-powered = cloud costs significatifs. 38% croissance = outils signés dans l\'urgence. Nouveau CFO en mode optimisation.',
      hiddenExposure: ['Cloud compute non-linéaire (AI models)', 'Dev tools per-seat scaling', 'Monitoring empilé', 'Contrats growth-sprint non renégociés'],
      proofNeeded: 'Scan stack AI/cloud pour identifier les cibles d\'optimisation.',
    },
    strengths: ['Nouveau CFO = cycle d\'audit', 'Même angle ironique que Circula', '400 emp = deal potential correct', 'Munich = DACH market'],
    weaknesses: ['CFO à 12 mois = peut avoir déjà fait son audit', 'Peut être moins réceptif qu\'à 3 mois', 'Signal moins urgent que top 4'],
    outreach: [
      { channel: 'linkedin', body: 'Gary,\n\nPricefx helps companies optimize their pricing — fair question: who optimizes Pricefx\'s own software spending?\n\nAt 38% subscription growth, tools get added faster than reviewed. A year into the CFO seat, you\'ve probably mapped the big lines. But the 12-18% that\'s invisible usually requires a structured scan to surface.\n\n48h, no call needed. Would it be useful?\n\n— Jean-Étienne', hook: 'Who optimizes the optimizer?', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: 'New CFO Gary Sher appointed March 2025', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 10000,
    nextAction: 'Trouver Gary Sher sur LinkedIn',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'pliant',
    company: 'Pliant',
    domain: 'getpliant.com',
    country: 'DE',
    industry: 'B2B Payments / Cards-as-a-Service',
    employeeRange: '200-300',
    website: 'https://getpliant.com',
    status: 'new',
    score: 23,
    tier: 2,
    attackability: 'soon',
    dealPotential: 'medium',
    conviction: 'high',
    solofit: 'ideal',
    financeLead: { name: 'Paul Harrald', title: 'CFO (Global)', background: 'CFO global gérant l\'expansion multi-marché dont le lancement US.' },
    signals: [
      { type: 'funding', detail: '$40M Series B (Apr 2025) — Illuminate Financial', source: 'Pliant PR', date: '2025-04', strength: 4 },
      { type: 'expansion', detail: 'Expansion US en cours', source: 'Company PR', strength: 4 },
      { type: 'growth', detail: '3,500+ clients, $100M+ total funding', source: 'Crunchbase', strength: 3 },
    ],
    mainSignal: 'Series B + expansion US = doublement de la complexité opérationnelle',
    whyNow: 'Expansion US d\'une fintech EU = deuxième couche compliance, cloud, outils. Le CFO gère le burn rate de l\'expansion.',
    hypothesis: {
      summary: 'Expansion US génère duplication: compliance EU vs US, cloud multi-région, outils support distincts.',
      whyItMatters: 'Chaque expansion multi-marché ajoute 20-30% au SaaS stack avant que quiconque ne le remarque.',
      hiddenExposure: ['Dual compliance EU/US', 'Cloud multi-région', 'Support/ops tools par marché', 'Series B cash discipline Illuminate'],
      proofNeeded: 'Scan pour mapper EU vs US stack overlap.',
    },
    strengths: ['CFO identifié', 'Taille idéale', 'Signal d\'expansion concret', 'Berlin fintech ecosystem'],
    weaknesses: ['Deal potential modéré', 'Expansion US = le CFO est très occupé', 'Signal moins urgent que restructuration/merger'],
    outreach: [
      { channel: 'linkedin', body: 'Paul,\n\nPliant is expanding to the US — which means a second layer of compliance tools, a second cloud region, and a second set of operational software. That transition typically adds 20-30% to the SaaS stack before anyone notices.\n\nI run exposure scans for fintech companies navigating this exact phase. Would that be useful?\n\n— Jean-Étienne', hook: 'US expansion = stack duplication', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: '$40M Series B + US expansion detected', date: NOW },
      { type: 'account_created', detail: 'Added from DACH prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 5000,
    nextAction: 'Trouver Paul Harrald sur LinkedIn',
    createdAt: NOW, updatedAt: NOW,
  },
  {
    id: 'finom',
    company: 'Finom',
    domain: 'finom.co',
    country: 'NL',
    industry: 'SME Banking / Financial Platform',
    employeeRange: '~500+',
    website: 'https://finom.co',
    status: 'new',
    score: 23,
    tier: 2,
    attackability: 'later',
    dealPotential: 'high',
    conviction: 'high',
    solofit: 'stretch',
    financeLead: { name: 'Alessandro Camilotti', title: 'CFO (ex-Klarna)', background: 'Ex-Klarna. Nommé Sep 2024. Connaît le scaling rapide fintech.' },
    signals: [
      { type: 'funding', detail: '€115M Series C (Jun 2025) + €92.7M General Catalyst', source: 'EU-Startups', date: '2025-06', strength: 5 },
      { type: 'expansion', detail: 'Expansion simultanée 5 marchés (DE, FR, IT, ES, NL)', source: 'Sifted', strength: 4 },
      { type: 'growth', detail: '125K+ clients, objectif 1M fin 2026', source: 'Company PR', strength: 4 },
    ],
    mainSignal: '€115M fraîches + expansion 5 pays simultanément',
    whyNow: 'Expansion 5 marchés = complexité opérationnelle exponentielle. Ex-Klarna CFO sait que le scaling crée du waste structurel.',
    hypothesis: {
      summary: '5 marchés = 5 régimes réglementaires, 5 sets d\'outils locaux. Le waste scale avec la complexité.',
      whyItMatters: 'Ex-Klarna CFO comprend que le scaling rapide crée du waste. Gère le burn rate sur 5 marchés.',
      hiddenExposure: ['5 compliance tool sets', 'Multi-country cloud', 'Local ops tools par marché', 'Vendor contracts à termes différents'],
      proofNeeded: 'Scan pour estimer le overhead opérationnel multi-marché.',
    },
    strengths: ['CFO ex-Klarna = profil très pertinent', '€115M fresh = peut payer', 'Deal potential élevé', 'Signal d\'expansion fort'],
    weaknesses: ['500+ emp = borderline corporate', 'Amsterdam HQ = distance culturelle', 'Expansion 5 pays = CFO ultra-occupé', 'Cycle de décision potentiellement plus long'],
    outreach: [
      { channel: 'linkedin', body: 'Alessandro,\n\n€115M fresh capital and simultaneous expansion into 5 European markets — the operational complexity must be scaling fast. Coming from Klarna, you know what happens to software costs during that kind of growth.\n\nI run exposure scans for fintech in your exact phase. Would that be useful?\n\n— Jean-Étienne', hook: '5-market expansion compound effect', status: 'draft' },
    ],
    timeline: [
      { type: 'signal_detected', detail: '€115M Series C + 5-country expansion detected', date: NOW },
      { type: 'account_created', detail: 'Added from NL/UK prospection batch', date: NOW },
    ],
    executionLog: [],
    revenueEstimate: 25000,
    nextAction: 'Trouver Alessandro Camilotti sur LinkedIn',
    createdAt: NOW, updatedAt: NOW,
  },
];
