"use client";
import { useState, useEffect, useRef } from "react";
import { useI18n } from "@/lib/i18n";
var V="#060912",A="#3b82f6",AH="#60a5fa",T1="#e0e6f2",T2="#8d9bb5",T3="#55637d",RD="#ef4444",OR="#f59e0b",TL="#34d399",BD="rgba(36,48,78,0.32)",MO="ui-monospace,'Cascadia Code','Fira Code',monospace",SA="system-ui,-apple-system,sans-serif";
var gl={background:"rgba(11,14,24,0.72)",backdropFilter:"blur(18px) saturate(1.15)",WebkitBackdropFilter:"blur(18px) saturate(1.15)",border:"1px solid "+BD,borderRadius:12,boxShadow:"0 4px 32px rgba(0,0,0,0.28)"};
function useReveal(th){var ref=useRef(null);var s=useState(false);var vis=s[0];var setVis=s[1];useEffect(function(){var el=ref.current;if(!el)return;var obs=new IntersectionObserver(function(e){if(e[0].isIntersecting){setVis(true);obs.disconnect();}},{threshold:th||0.1});obs.observe(el);return function(){obs.disconnect();};},[th]);return[ref,vis];}
function Panel(props){var r=useReveal(0.08);return(<div ref={r[0]} style={Object.assign({},gl,{padding:props.pad||22,opacity:r[1]?1:0,transform:r[1]?"translateY(0)":"translateY(14px)",transition:"all 0.55s cubic-bezier(0.16,1,0.3,1) "+(props.delay||0)+"ms"},props.st||{})}>{props.children}</div>);}
function Lab(p){return <span style={{display:"block",fontSize:9,fontWeight:600,fontFamily:MO,letterSpacing:".14em",textTransform:"uppercase",color:A,marginBottom:10}}>{p.children}</span>;}
function Ttl(p){return <h2 style={{fontSize:19,fontWeight:700,color:T1,lineHeight:1.2,letterSpacing:"-.01em",marginBottom:10}}>{p.children}</h2>;}
function EntropyExplorer({t}){var st=useState(160);var emp=st[0];var setEmp=st[1];var k=emp<=50?0:Math.min(0.40,0.12*Math.log(emp/50));var boost=k*100;var pts="";for(var j=0;j<50;j++){var nn=10+j*10;var kk=nn<=50?0:Math.min(0.40,0.12*Math.log(nn/50));pts+=(j>0?" ":"")+((nn/500)*280+10)+","+(100-(kk/0.45)*90);}var mx=(emp/500)*280+10,my=100-(k/0.45)*90,dy=100-(0.20/0.45)*90;
return(<div style={{display:"flex",flexDirection:"column",gap:14}}>
<div style={{padding:18,borderRadius:8,background:"rgba(59,130,246,0.04)",border:"1px solid rgba(59,130,246,0.12)",textAlign:"center"}}><div style={{fontFamily:MO,fontSize:20,fontWeight:700,lineHeight:1.6}}><span style={{color:A}}>κ</span><span style={{color:T3}}>(</span><span style={{color:OR}}>N</span><span style={{color:T3}}>)</span><span style={{color:T3,margin:"0 6px"}}>=</span><span style={{color:T2}}>0.12</span><span style={{color:T3,margin:"0 4px"}}>×</span><span style={{color:T2}}>ln</span><span style={{color:T3}}>(</span><span style={{color:OR}}>N</span><span style={{color:T3}}>/</span><span style={{color:T2}}>50</span><span style={{color:T3}}>)</span></div><p style={{fontSize:10,color:T3,marginTop:6}}>α = 0.12 · N₀ = 50 · κ ∈ [0, 0.40]</p></div>
<div><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:10,color:T3,textTransform:"uppercase",letterSpacing:".08em"}}>{t("method.s2.headcount")}</span><span style={{fontFamily:MO,fontSize:16,fontWeight:700,color:AH}}>{emp}</span></div><input type="range" min={10} max={500} step={10} value={emp} onChange={function(e){setEmp(Number(e.target.value));}} style={{width:"100%",accentColor:A}}/></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
<div style={{padding:12,borderRadius:8,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.18)",textAlign:"center"}}><p style={{fontSize:9,color:T3,textTransform:"uppercase",letterSpacing:".08em",marginBottom:2}}>Entropy κ</p><p style={{fontFamily:MO,fontSize:22,fontWeight:800,color:k>0.20?OR:A}}>{k.toFixed(3)}</p></div>
<div style={{padding:12,borderRadius:8,background:k>0.20?"rgba(239,68,68,0.05)":"rgba(52,211,153,0.05)",border:"1px solid "+(k>0.20?"rgba(239,68,68,0.14)":"rgba(52,211,153,0.14)"),textAlign:"center"}}><p style={{fontSize:9,color:T3,textTransform:"uppercase",letterSpacing:".08em",marginBottom:2}}>Amplification</p><p style={{fontFamily:MO,fontSize:22,fontWeight:800,color:k>0.20?RD:TL}}>+{boost.toFixed(1)}%</p></div>
</div>
<svg viewBox="0 0 300 120" style={{width:"100%",display:"block"}}>
{[0.1,0.2,0.3,0.4].map(function(v){var gy=100-(v/0.45)*90;return(<g key={v}><line x1="10" y1={gy} x2="290" y2={gy} stroke="rgba(36,48,78,0.25)" strokeWidth="0.5" strokeDasharray="4,4"/><text x="296" y={gy+3} fill={T3} fontSize="7" fontFamily={MO}>{v.toFixed(1)}</text></g>);})}
{[50,100,200,300,400,500].map(function(n){return <text key={n} x={(n/500)*280+10} y="115" fill={T3} fontSize="7" fontFamily={MO} textAnchor="middle">{n}</text>;})}
<rect x="10" y={dy} width="280" height={100-dy} fill="rgba(239,68,68,0.03)"/>
<line x1="10" y1={dy} x2="290" y2={dy} stroke={RD} strokeWidth="0.5" strokeDasharray="6,3" opacity="0.35"/>
<polyline points={pts} fill="none" stroke={A} strokeWidth="2" strokeLinejoin="round"/>
<circle cx={mx} cy={my} r="5" fill={k>0.20?RD:A} stroke={V} strokeWidth="2"/>
<circle cx={mx} cy={my} r="10" fill="none" stroke={k>0.20?RD:A} strokeWidth="1" opacity="0.3"><animate attributeName="r" values="8;14;8" dur="2s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.4;0;0.4" dur="2s" repeatCount="indefinite"/></circle>
</svg>
<p style={{fontSize:12,color:T2,lineHeight:1.5}}>{k===0?t("method.entropy.zero"):k<0.10?t("method.entropy.low"):k<0.20?t("method.entropy.mod"):t("method.entropy.high")}</p>
</div>);}
export default function Methodology(){var { t } = useI18n();
var LEAKS=[{i:"👻",n:t("method.leak.1"),s:"CRIT",c:RD,p:"28%",d:t("method.leak.1d")},{i:"🔄",n:t("method.leak.2"),s:"HIGH",c:OR,p:"18%",d:t("method.leak.2d")},{i:"📐",n:t("method.leak.3"),s:"HIGH",c:OR,p:"14%",d:t("method.leak.3d")},{i:"🏴",n:t("method.leak.4"),s:"CRIT",c:RD,p:"12%",d:t("method.leak.4d")},{i:"📈",n:t("method.leak.5"),s:"HIGH",c:OR,p:"8%",d:t("method.leak.5d")},{i:"🔌",n:t("method.leak.6"),s:"MED",c:"#d4a72c",p:"6%",d:t("method.leak.6d")},{i:"🔁",n:t("method.leak.7"),s:"MED",c:"#d4a72c",p:"5%",d:t("method.leak.7d")},{i:"☁️",n:t("method.leak.8"),s:"MED",c:"#d4a72c",p:"4%",d:t("method.leak.8d")},{i:"💸",n:t("method.leak.9"),s:"HIGH",c:OR,p:"3%",d:t("method.leak.9d")},{i:"📉",n:t("method.leak.10"),s:"CRIT",c:RD,p:"7%",d:t("method.leak.10d")},{i:"🤖",n:t("method.leak.11"),s:"CRIT",c:RD,p:"9%",d:t("method.leak.11d")},{i:"🔒",n:t("method.leak.12"),s:"HIGH",c:OR,p:"—",d:t("method.leak.12d")}];
var ZK=[{n:"01",t:t("method.zk.step1"),d:t("method.zk.step1d"),ic:"📤"},{n:"02",t:t("method.zk.step2"),d:t("method.zk.step2d"),ic:"🔒"},{n:"03",t:t("method.zk.step3"),d:t("method.zk.step3d"),ic:"⚡"},{n:"04",t:t("method.zk.step4"),d:t("method.zk.step4d"),ic:"📊"}];
var TH=[[t("method.th.aiwriting"),"1"],[t("method.th.aicoding"),"1"],[t("method.th.analytics"),"1"],[t("method.th.comms"),"1"],[t("method.th.projmgmt"),"1"],[t("method.th.crm"),"1"],[t("method.th.design"),"2"],[t("method.th.cloud"),"2"],[t("method.th.security"),"2"],[t("method.th.aiplatforms"),"2"],[t("method.th.storage"),"1"]];
var HON=[{text:t("method.hon.1"),v:"V2"},{text:t("method.hon.2"),v:"V3"},{text:t("method.hon.3"),v:"V2"},{text:t("method.hon.4"),v:"V2"},{text:t("method.hon.5"),v:"V2"}];
return(
<div style={{minHeight:"100vh",background:V,fontFamily:SA,color:T1,padding:"0 14px 64px"}}><div style={{maxWidth:1020,margin:"0 auto"}}>
<div style={{paddingTop:16}}><a href="/" style={{display:"inline-flex",alignItems:"center",gap:6,fontSize:11,color:T2,textDecoration:"none",padding:"6px 12px",borderRadius:6,border:"1px solid "+BD,background:"rgba(11,14,24,0.5)",transition:"color 0.15s"}}>{t("back")}</a></div>
<header style={{textAlign:"center",padding:"36px 0 40px"}}>
<p style={{fontSize:9,fontWeight:600,letterSpacing:".16em",textTransform:"uppercase",color:A,fontFamily:MO,marginBottom:14}}>{t("method.badge")}</p>
<h1 style={{fontSize:"clamp(26px,4vw,40px)",fontWeight:800,lineHeight:1.1,letterSpacing:"-.025em",marginBottom:14}}>{t("method.title1")} <span style={{color:A}}>{t("method.title2")}</span> <span style={{color:RD}}>{t("method.title3")}</span></h1>
<p style={{fontSize:15,color:T2,maxWidth:540,margin:"0 auto",lineHeight:1.6}}>{t("method.subtitle")}</p>
<div style={{display:"flex",justifyContent:"center",gap:10,marginTop:20,flexWrap:"wrap"}}>{[t("method.tags.1"),t("method.tags.2"),t("method.tags.3"),t("method.tags.4")].map(function(b){return <span key={b} style={{fontSize:9,fontWeight:600,fontFamily:MO,letterSpacing:".06em",textTransform:"uppercase",padding:"4px 10px",borderRadius:5,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.18)",color:AH}}>{b}</span>;})}</div>
</header>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"7fr 5fr",gap:14}}>
<Panel><Lab>{t("method.s1.label")}</Lab><Ttl>{t("method.s1.title")}</Ttl><p style={{fontSize:13,color:T2,lineHeight:1.6,marginBottom:14}}>{t("method.s1.p1")} <strong style={{color:T1}}>{t("method.s1.p1b")}</strong>{t("method.s1.p1c")}</p>
<div style={{padding:14,borderRadius:8,background:"rgba(0,0,0,0.18)",border:"1px solid rgba(36,48,78,0.22)",fontFamily:MO,fontSize:11,lineHeight:1.8,color:T2}}>
<div style={{color:T3,marginBottom:6,fontSize:9,letterSpacing:".08em"}}>{t("method.s1.algo")}</div>
<div><span style={{color:A}}>for each</span> category ∈ [ai_writing, design, ...]</div>
<div style={{paddingLeft:16}}><span style={{color:A}}>if</span> tool_count {">"} threshold[category]</div>
<div style={{paddingLeft:32}}>excess ← sort_by_cost(tools)[threshold:]</div>
<div style={{paddingLeft:32}}>cost ← Σ(excess.monthly) <span style={{color:OR}}>× √(N/50)</span></div>
</div></Panel>
<Panel delay={100}><Lab>{t("method.s1.thresholds")}</Lab><div style={{display:"flex",flexDirection:"column",gap:6}}>{TH.map(function(th){return(<div key={th[0]} style={{display:"flex",justifyContent:"space-between",padding:"5px 10px",borderRadius:5,background:"rgba(0,0,0,0.14)",fontSize:11}}><span style={{color:T2}}>{th[0]}</span><span style={{fontFamily:MO,fontWeight:700,color:th[1]==="1"?TL:AH,fontSize:12}}>≤ {th[1]}</span></div>);})}</div><p style={{fontSize:10,color:T3,marginTop:10,fontStyle:"italic"}}>{t("method.s1.threshnote")}</p></Panel>
</section>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"7fr 5fr",gap:14}}>
<Panel><Lab>{t("method.s2.label")}</Lab><Ttl>{t("method.s2.title1")} <span style={{color:RD}}>{t("method.s2.title2")}</span> {t("method.s2.title3")}</Ttl><p style={{fontSize:13,color:T2,lineHeight:1.6,marginBottom:14}}>{t("method.s2.desc")} <strong style={{color:T1}}>{t("method.s2.descb")}</strong>{t("method.s2.descc")}</p><EntropyExplorer t={t}/></Panel>
<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Panel delay={100}><Lab>{t("method.s3.label")}</Lab><Ttl>{t("method.s3.title")}</Ttl><div style={{display:"flex",flexDirection:"column",gap:7}}>{[["🚫",t("method.zk.1")],["🚫",t("method.zk.2")],["🚫",t("method.zk.3")],["🔐",t("method.zk.4")],["🗑️",t("method.zk.5")],["🇺🇸",t("method.zk.6")]].map(function(x,j){return(<div key={j} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 10px",borderRadius:5,background:x[0]==="🚫"?"rgba(239,68,68,0.03)":"rgba(52,211,153,0.03)",border:"1px solid "+(x[0]==="🚫"?"rgba(239,68,68,0.10)":"rgba(52,211,153,0.10)"),fontSize:11,color:T2}}><span style={{fontSize:13}}>{x[0]}</span>{x[1]}</div>);})}</div></Panel>
<Panel delay={200} pad={16}><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{fontSize:20}}>🛡</span><div><p style={{fontSize:11,fontWeight:600,color:T1}}>{t("method.zk.trust")}</p><p style={{fontSize:10,color:T3,lineHeight:1.4}}>{t("method.zk.trustsub")}</p></div></div></Panel>
</div></section>
<section style={{marginBottom:40}}><Panel><Lab>{t("method.s4.label")}</Lab><Ttl>{t("method.s4.title")}</Ttl><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginTop:16}}>{ZK.map(function(s){return(<div key={s.n} style={{padding:"16px 14px",borderRadius:10,background:"rgba(0,0,0,0.16)",border:"1px solid rgba(36,48,78,0.20)",position:"relative"}}><div style={{fontFamily:MO,fontSize:28,fontWeight:800,color:"rgba(59,130,246,0.07)",position:"absolute",top:10,right:12}}>{s.n}</div><span style={{fontSize:22}}>{s.ic}</span><h3 style={{fontSize:14,fontWeight:700,color:T1,marginTop:8,marginBottom:4}}>{s.t}</h3><p style={{fontSize:11,color:T2,lineHeight:1.5}}>{s.d}</p></div>);})}</div></Panel></section>
<section style={{marginBottom:40}}><Panel><Lab>{t("method.s5.label")}</Lab><Ttl>{t("method.s5.title")}</Ttl><p style={{fontSize:12,color:T2,lineHeight:1.5,marginBottom:16}}>{t("method.s5.source")}</p><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{LEAKS.map(function(l){return(<div key={l.n} style={{padding:"12px 10px",borderRadius:7,background:"rgba(0,0,0,0.16)",border:"1px solid rgba(36,48,78,0.18)",transition:"border-color 0.2s",cursor:"default"}} onMouseEnter={function(e){e.currentTarget.style.borderColor=l.c+"40";}} onMouseLeave={function(e){e.currentTarget.style.borderColor="rgba(36,48,78,0.18)";}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:18}}>{l.i}</span><span style={{fontSize:8,fontWeight:600,fontFamily:MO,padding:"2px 5px",borderRadius:3,color:l.c,background:l.c+"14",border:"1px solid "+l.c+"28"}}>{l.s}</span></div><h4 style={{fontSize:12,fontWeight:600,color:T1,marginBottom:3}}>{l.n}</h4><p style={{fontSize:10,color:T3,lineHeight:1.3,marginBottom:4}}>{l.d}</p>{l.p!=="—"&&<span style={{fontFamily:MO,fontSize:11,fontWeight:700,color:T2}}>~{l.p}</span>}</div>);})}</div></Panel></section>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"8fr 4fr",gap:14}}>
<Panel><Lab>{t("method.s6.label")}</Lab><Ttl>{t("method.s6.title")}</Ttl><div style={{display:"flex",flexDirection:"column",gap:6}}>{HON.map(function(h,j){return(<div key={j} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 12px",borderRadius:6,background:"rgba(0,0,0,0.12)",border:"1px solid rgba(36,48,78,0.12)"}}><span style={{fontSize:11,color:T2}}>{h.text}</span><span style={{fontSize:9,fontFamily:MO,fontWeight:600,padding:"2px 7px",borderRadius:4,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.16)",color:AH}}>{h.v}</span></div>);})}</div></Panel>
<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Panel delay={80}><Lab>{t("method.noml.label")}</Lab>{[["01",t("method.noml.1")],["02",t("method.noml.2")],["03",t("method.noml.3")],["04",t("method.noml.4")]].map(function(x){return(<div key={x[0]} style={{display:"flex",gap:8,marginBottom:8}}><span style={{fontFamily:MO,fontSize:10,fontWeight:700,color:A,minWidth:20}}>{x[0]}</span><span style={{fontSize:11,color:T2,lineHeight:1.4}}>{x[1]}</span></div>);})}</Panel>
<Panel delay={160}><div style={{textAlign:"center"}}><p style={{fontSize:12,color:T2,marginBottom:14}}>{t("method.cta.text")}</p><a href="/estimator" style={{display:"inline-block",padding:"11px 22px",borderRadius:8,background:A,color:"#fff",fontSize:11,fontWeight:700,letterSpacing:".05em",textTransform:"uppercase",textDecoration:"none"}}>{t("method.cta")} →</a><p style={{fontSize:10,color:T3,marginTop:8}}>{t("method.cta.sub")}</p></div></Panel>
</div></section>
</div></div>);}
