"use client";
import { useState, useEffect, useRef } from "react";
var V="#060912",A="#3b82f6",AH="#60a5fa",T1="#e0e6f2",T2="#8d9bb5",T3="#55637d",RD="#ef4444",OR="#f59e0b",TL="#34d399",BD="rgba(36,48,78,0.32)",MO="ui-monospace,'Cascadia Code','Fira Code',monospace",SA="system-ui,-apple-system,sans-serif";
var gl={background:"rgba(11,14,24,0.72)",backdropFilter:"blur(18px) saturate(1.15)",WebkitBackdropFilter:"blur(18px) saturate(1.15)",border:"1px solid "+BD,borderRadius:12,boxShadow:"0 4px 32px rgba(0,0,0,0.28)"};
function useReveal(th){var ref=useRef(null);var s=useState(false);var vis=s[0];var setVis=s[1];useEffect(function(){var el=ref.current;if(!el)return;var obs=new IntersectionObserver(function(e){if(e[0].isIntersecting){setVis(true);obs.disconnect();}},{threshold:th||0.1});obs.observe(el);return function(){obs.disconnect();};},[th]);return[ref,vis];}
function Panel(props){var r=useReveal(0.08);return(<div ref={r[0]} style={Object.assign({},gl,{padding:props.pad||22,opacity:r[1]?1:0,transform:r[1]?"translateY(0)":"translateY(14px)",transition:"all 0.55s cubic-bezier(0.16,1,0.3,1) "+(props.delay||0)+"ms"},props.st||{})}>{props.children}</div>);}
function Lab(p){return <span style={{display:"block",fontSize:9,fontWeight:600,fontFamily:MO,letterSpacing:".14em",textTransform:"uppercase",color:A,marginBottom:10}}>{p.children}</span>;}
function Ttl(p){return <h2 style={{fontSize:19,fontWeight:700,color:T1,lineHeight:1.2,letterSpacing:"-.01em",marginBottom:10}}>{p.children}</h2>;}
var LEAKS=[{i:"👻",n:"Inactive Licenses",s:"CRIT",c:RD,p:"28%",d:"Seats paid for departed or idle employees (90+ days)."},{i:"🔄",n:"Redundant Tools",s:"HIGH",c:OR,p:"18%",d:"Multiple tools solving the same function across teams."},{i:"📐",n:"Oversized Plans",s:"HIGH",c:OR,p:"14%",d:"Enterprise tier for basic-level usage."},{i:"🏴",n:"Shadow IT",s:"CRIT",c:RD,p:"12%",d:"Tools bought without IT approval."},{i:"📈",n:"Rate Spike",s:"HIGH",c:OR,p:"8%",d:"30%+ MoM increase with no justification."},{i:"🔌",n:"Unused Modules",s:"MED",c:"#d4a72c",p:"6%",d:"Paid add-ons never activated."},{i:"🔁",n:"Contract Drift",s:"MED",c:"#d4a72c",p:"5%",d:"Auto-renewed at silently increased rates."},{i:"☁️",n:"Orphan Resources",s:"MED",c:"#d4a72c",p:"4%",d:"Cloud resources with no owner."},{i:"💸",n:"Billing Errors",s:"HIGH",c:OR,p:"3%",d:"Overcharges, duplicate invoices."},{i:"📉",n:"Commitment Waste",s:"CRIT",c:RD,p:"7%",d:"Annual contracts utilized below 60%."},{i:"🤖",n:"AI Cost Drift",s:"CRIT",c:RD,p:"9%",d:"Exponential token growth, zero governance."},{i:"🔒",n:"Vendor Lock-in",s:"HIGH",c:OR,p:"—",d:"40%+ budget on a single vendor."}];
var ZK=[{n:"01",t:"You Export",d:"Download CSVs from billing tools. You control what leaves.",ic:"📤"},{n:"02",t:"You Upload",d:"Encrypted TLS 1.3. Files never touch human hands.",ic:"🔒"},{n:"03",t:"Engine Analyzes",d:"8 detectors in isolated container. No human reads raw files.",ic:"⚡"},{n:"04",t:"You Receive",d:"Structured report with dollar-valued recovery actions.",ic:"📊"}];
var TH=[["AI Writing","1"],["AI Coding","1"],["Analytics","1"],["Comms","1"],["Project Mgmt","1"],["CRM","1"],["Design","2"],["Cloud","2"],["Security","2"],["AI Platforms","2"],["Storage","1"]];
var HON=[["No direct vendor API connections","V2"],["No ML (deterministic = explainable)","V3"],["No cross-client benchmarks","V2"],["No real-time detection","V2"],["No per-department scoring","V2"]];
function EntropyExplorer(){var st=useState(160);var emp=st[0];var setEmp=st[1];var k=emp<=50?0:Math.min(0.40,0.12*Math.log(emp/50));var boost=k*100;var pts="";for(var j=0;j<50;j++){var nn=10+j*10;var kk=nn<=50?0:Math.min(0.40,0.12*Math.log(nn/50));pts+=(j>0?" ":"")+((nn/500)*280+10)+","+(100-(kk/0.45)*90);}var mx=(emp/500)*280+10,my=100-(k/0.45)*90,dy=100-(0.20/0.45)*90;
return(<div style={{display:"flex",flexDirection:"column",gap:14}}>
<div style={{padding:18,borderRadius:8,background:"rgba(59,130,246,0.04)",border:"1px solid rgba(59,130,246,0.12)",textAlign:"center"}}><div style={{fontFamily:MO,fontSize:20,fontWeight:700,lineHeight:1.6}}><span style={{color:A}}>κ</span><span style={{color:T3}}>(</span><span style={{color:OR}}>N</span><span style={{color:T3}}>)</span><span style={{color:T3,margin:"0 6px"}}>=</span><span style={{color:T2}}>0.12</span><span style={{color:T3,margin:"0 4px"}}>×</span><span style={{color:T2}}>ln</span><span style={{color:T3}}>(</span><span style={{color:OR}}>N</span><span style={{color:T3}}>/</span><span style={{color:T2}}>50</span><span style={{color:T3}}>)</span></div><p style={{fontSize:10,color:T3,marginTop:6}}>α = 0.12 · N₀ = 50 · κ ∈ [0, 0.40]</p></div>
<div><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:10,color:T3,textTransform:"uppercase",letterSpacing:".08em"}}>Headcount</span><span style={{fontFamily:MO,fontSize:16,fontWeight:700,color:AH}}>{emp}</span></div><input type="range" min={10} max={500} step={10} value={emp} onChange={function(e){setEmp(Number(e.target.value));}} style={{width:"100%",accentColor:A}}/></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
<div style={{padding:12,borderRadius:8,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.18)",textAlign:"center"}}><p style={{fontSize:9,color:T3,textTransform:"uppercase",letterSpacing:".08em",marginBottom:2}}>Entropy κ</p><p style={{fontFamily:MO,fontSize:22,fontWeight:800,color:k>0.20?OR:A}}>{k.toFixed(3)}</p></div>
<div style={{padding:12,borderRadius:8,background:k>0.20?"rgba(239,68,68,0.05)":"rgba(52,211,153,0.05)",border:"1px solid "+(k>0.20?"rgba(239,68,68,0.14)":"rgba(52,211,153,0.14)"),textAlign:"center"}}><p style={{fontSize:9,color:T3,textTransform:"uppercase",letterSpacing:".08em",marginBottom:2}}>Amplification</p><p style={{fontFamily:MO,fontSize:22,fontWeight:800,color:k>0.20?RD:TL}}>+{boost.toFixed(1)}%</p></div>
</div>
<svg viewBox="0 0 300 120" style={{width:"100%",display:"block"}}>
{[0.1,0.2,0.3,0.4].map(function(v){var gy=100-(v/0.45)*90;return(<g key={v}><line x1="10" y1={gy} x2="290" y2={gy} stroke="rgba(36,48,78,0.25)" strokeWidth="0.5" strokeDasharray="4,4"/><text x="296" y={gy+3} fill={T3} fontSize="7" fontFamily={MO}>{v.toFixed(1)}</text></g>);})}
{[50,100,200,300,400,500].map(function(n){return <text key={n} x={(n/500)*280+10} y="115" fill={T3} fontSize="7" fontFamily={MO} textAnchor="middle">{n}</text>;})}
<rect x="10" y={dy} width="280" height={100-dy} fill="rgba(239,68,68,0.03)"/>
<line x1="10" y1={dy} x2="290" y2={dy} stroke={RD} strokeWidth="0.5" strokeDasharray="6,3" opacity="0.35"/>
<polyline points={pts} fill="none" stroke={A} strokeWidth="2" strokeLinejoin="round"/>
<circle cx={mx} cy={my} r="5" fill={k>0.20?RD:A} stroke={V} strokeWidth="2"/>
<circle cx={mx} cy={my} r="10" fill="none" stroke={k>0.20?RD:A} strokeWidth="1" opacity="0.3"><animate attributeName="r" values="8;14;8" dur="2s" repeatCount="indefinite"/><animate attributeName="opacity" values="0.4;0;0.4" dur="2s" repeatCount="indefinite"/></circle>
</svg>
<p style={{fontSize:12,color:T2,lineHeight:1.5}}>{k===0?"Compact org (≤50). Entropy is zero — one person governs all purchases.":k<0.10?"Low entropy. Coordination manageable, but duplicates appear at team boundaries.":k<0.20?"Moderate entropy. Shadow IT and orphan licenses increasing. Monitoring recommended.":"High entropy. Leaks near-inevitable without active FinOps governance. Audit urgent."}</p>
</div>);}
export default function Methodology(){return(
<div style={{minHeight:"100vh",background:V,fontFamily:SA,color:T1,padding:"0 14px 64px"}}><div style={{maxWidth:1020,margin:"0 auto"}}>
<header style={{textAlign:"center",padding:"52px 0 40px"}}>
<p style={{fontSize:9,fontWeight:600,letterSpacing:".16em",textTransform:"uppercase",color:A,fontFamily:MO,marginBottom:14}}>QUANTITATIVE METHODOLOGY</p>
<h1 style={{fontSize:"clamp(26px,4vw,40px)",fontWeight:800,lineHeight:1.1,letterSpacing:"-.025em",marginBottom:14}}>12 leak types. <span style={{color:A}}>1 engine.</span> <span style={{color:RD}}>0 blind spots.</span></h1>
<p style={{fontSize:15,color:T2,maxWidth:540,margin:"0 auto",lineHeight:1.6}}>A deterministic, explainable, and verifiable engine. We publish our thresholds, formulas, and limitations.</p>
<div style={{display:"flex",justifyContent:"center",gap:10,marginTop:20,flexWrap:"wrap"}}>{["Deterministic","Zero ML V1","Explainable","Open Methodology"].map(function(b){return <span key={b} style={{fontSize:9,fontWeight:600,fontFamily:MO,letterSpacing:".06em",textTransform:"uppercase",padding:"4px 10px",borderRadius:5,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.18)",color:AH}}>{b}</span>;})}</div>
</header>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"7fr 5fr",gap:14}}>
<Panel><Lab>01 — SHADOW AI INFERENCE</Lab><Ttl>Detect redundancy without accessing your systems.</Ttl><p style={{fontSize:13,color:T2,lineHeight:1.6,marginBottom:14}}>The engine operates by <strong style={{color:T1}}>inference on billing data</strong>: each tool maps to a functional category. Excess tools beyond the optimal threshold trigger redundancy cost weighted by √(N/50).</p>
<div style={{padding:14,borderRadius:8,background:"rgba(0,0,0,0.18)",border:"1px solid rgba(36,48,78,0.22)",fontFamily:MO,fontSize:11,lineHeight:1.8,color:T2}}>
<div style={{color:T3,marginBottom:6,fontSize:9,letterSpacing:".08em"}}>DETECTION ALGORITHM</div>
<div><span style={{color:A}}>for each</span> category ∈ [ai_writing, design, ...]</div>
<div style={{paddingLeft:16}}><span style={{color:A}}>if</span> tool_count {">"} threshold[category]</div>
<div style={{paddingLeft:32}}>excess ← sort_by_cost(tools)[threshold:]</div>
<div style={{paddingLeft:32}}>cost ← Σ(excess.monthly) <span style={{color:OR}}>× √(N/50)</span></div>
</div></Panel>
<Panel delay={100}><Lab>OPTIMAL THRESHOLDS</Lab><div style={{display:"flex",flexDirection:"column",gap:6}}>{TH.map(function(t){return(<div key={t[0]} style={{display:"flex",justifyContent:"space-between",padding:"5px 10px",borderRadius:5,background:"rgba(0,0,0,0.14)",fontSize:11}}><span style={{color:T2}}>{t[0]}</span><span style={{fontFamily:MO,fontWeight:700,color:t[1]==="1"?TL:AH,fontSize:12}}>≤ {t[1]}</span></div>);})}</div><p style={{fontSize:10,color:T3,marginTop:10,fontStyle:"italic"}}>Above threshold = billable redundancy. Zylo 2024 + Flexera 2024.</p></Panel>
</section>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"7fr 5fr",gap:14}}>
<Panel><Lab>02 — THE ENTROPY EQUATION</Lab><Ttl>As organizations grow, the <span style={{color:RD}}>Ghost Tax</span> accelerates.</Ttl><p style={{fontSize:13,color:T2,lineHeight:1.6,marginBottom:14}}>κ(N) models Brooks' Law for IT spend: coordination cost grows at <strong style={{color:T1}}>O(n log n)</strong>. The logarithm captures natural stabilization — 500 employees is not 10x more chaotic than 50.</p><EntropyExplorer/></Panel>
<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Panel delay={100}><Lab>03 — ZERO-KNOWLEDGE PROTOCOL</Lab><Ttl>Your systems stay untouched.</Ttl><div style={{display:"flex",flexDirection:"column",gap:7}}>{[["🚫","No agents on your machines"],["🚫","No OAuth connections"],["🚫","No network access"],["🔐","TLS 1.3 + AES-256"],["🗑️","Auto-deleted day 30"],["🇺🇸","US data residency (VA)"]].map(function(x,j){return(<div key={j} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 10px",borderRadius:5,background:x[0]==="🚫"?"rgba(239,68,68,0.03)":"rgba(52,211,153,0.03)",border:"1px solid "+(x[0]==="🚫"?"rgba(239,68,68,0.10)":"rgba(52,211,153,0.10)"),fontSize:11,color:T2}}><span style={{fontSize:13}}>{x[0]}</span>{x[1]}</div>);})}</div></Panel>
<Panel delay={200} pad={16}><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{fontSize:20}}>🛡</span><div><p style={{fontSize:11,fontWeight:600,color:T1}}>Less access = less risk</p><p style={{fontSize:10,color:T3,lineHeight:1.4}}>Zero-Knowledge is architectural, not a limitation.</p></div></div></Panel>
</div></section>
<section style={{marginBottom:40}}><Panel><Lab>04 — FOUR-PHASE PROCESS</Lab><Ttl>From CSV to board report in 48 hours.</Ttl><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginTop:16}}>{ZK.map(function(s){return(<div key={s.n} style={{padding:"16px 14px",borderRadius:10,background:"rgba(0,0,0,0.16)",border:"1px solid rgba(36,48,78,0.20)",position:"relative"}}><div style={{fontFamily:MO,fontSize:28,fontWeight:800,color:"rgba(59,130,246,0.07)",position:"absolute",top:10,right:12}}>{s.n}</div><span style={{fontSize:22}}>{s.ic}</span><h3 style={{fontSize:14,fontWeight:700,color:T1,marginTop:8,marginBottom:4}}>{s.t}</h3><p style={{fontSize:11,color:T2,lineHeight:1.5}}>{s.d}</p></div>);})}</div></Panel></section>
<section style={{marginBottom:40}}><Panel><Lab>05 — 12-TYPE LEAK TAXONOMY</Lab><Ttl>Every lost dollar has a name, a type, and a recovery path.</Ttl><p style={{fontSize:12,color:T2,lineHeight:1.5,marginBottom:16}}>Covers 95%+ of SaaS/Cloud/AI losses. Sources: Flexera 2024, Zylo 2024, Gartner 2025.</p><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{LEAKS.map(function(l){return(<div key={l.n} style={{padding:"12px 10px",borderRadius:7,background:"rgba(0,0,0,0.16)",border:"1px solid rgba(36,48,78,0.18)",transition:"border-color 0.2s",cursor:"default"}} onMouseEnter={function(e){e.currentTarget.style.borderColor=l.c+"40";}} onMouseLeave={function(e){e.currentTarget.style.borderColor="rgba(36,48,78,0.18)";}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:18}}>{l.i}</span><span style={{fontSize:8,fontWeight:600,fontFamily:MO,padding:"2px 5px",borderRadius:3,color:l.c,background:l.c+"14",border:"1px solid "+l.c+"28"}}>{l.s}</span></div><h4 style={{fontSize:12,fontWeight:600,color:T1,marginBottom:3}}>{l.n}</h4><p style={{fontSize:10,color:T3,lineHeight:1.3,marginBottom:4}}>{l.d}</p>{l.p!=="—"&&<span style={{fontFamily:MO,fontSize:11,fontWeight:700,color:T2}}>~{l.p}</span>}</div>);})}</div></Panel></section>
<section style={{marginBottom:40,display:"grid",gridTemplateColumns:"8fr 4fr",gap:14}}>
<Panel><Lab>06 — WHAT V1 DOES NOT DO</Lab><Ttl>Honesty over marketing.</Ttl><div style={{display:"flex",flexDirection:"column",gap:6}}>{HON.map(function(h,j){return(<div key={j} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 12px",borderRadius:6,background:"rgba(0,0,0,0.12)",border:"1px solid rgba(36,48,78,0.12)"}}><span style={{fontSize:11,color:T2}}>{h[0]}</span><span style={{fontSize:9,fontFamily:MO,fontWeight:600,padding:"2px 7px",borderRadius:4,background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.16)",color:AH}}>{h[1]}</span></div>);})}</div></Panel>
<div style={{display:"flex",flexDirection:"column",gap:14}}>
<Panel delay={80}><Lab>WHY NO ML IN V1?</Lab>{[["01","Explainable — CFO understands every alert"],["02","Reproducible — same input, same output"],["03","Zero hallucination — no AI false positives"],["04","Instant — under 50ms, no API call"]].map(function(x){return(<div key={x[0]} style={{display:"flex",gap:8,marginBottom:8}}><span style={{fontFamily:MO,fontSize:10,fontWeight:700,color:A,minWidth:20}}>{x[0]}</span><span style={{fontSize:11,color:T2,lineHeight:1.4}}>{x[1]}</span></div>);})}</Panel>
<Panel delay={160}><div style={{textAlign:"center"}}><p style={{fontSize:12,color:T2,marginBottom:14}}>Test this methodology on your own data.</p><a href="/en-us/estimator" style={{display:"inline-block",padding:"11px 22px",borderRadius:8,background:A,color:"#fff",fontSize:11,fontWeight:700,letterSpacing:".05em",textTransform:"uppercase",textDecoration:"none"}}>EXPOSE MY GHOST TAX →</a><p style={{fontSize:10,color:T3,marginTop:8}}>60s · Free · No sensitive data needed</p></div></Panel>
</div></section>
</div></div>);}
